<?php
/**
 * Plugin Name: AJAX DB Form Saver
 * Description: Provides a shortcode [ajax_db_form] to display a contact form that saves submissions via AJAX to a custom post type, viewable in the admin panel.
 * Version: 2.0.0
 * Author: AutoGenerated
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class Ajax_DB_Form_Saver {

    public function __construct() {
        add_shortcode( 'ajax_db_form', [ $this, 'render_form' ] );
        add_action( 'wp_enqueue_scripts', [ $this, 'enqueue_assets' ] );
        add_action( 'wp_ajax_nopriv_ajax_db_form_submit', [ $this, 'handle_form_submit' ] );
        add_action( 'wp_ajax_ajax_db_form_submit', [ $this, 'handle_form_submit' ] );
        add_action( 'init', [ $this, 'register_post_type' ] );
        add_action( 'init', [ $this, 'register_taxonomy' ] );
        add_action( 'add_meta_boxes', [ $this, 'add_entry_meta_box' ] );
        add_filter( 'manage_ajax_form_entry_posts_columns', [ $this, 'admin_columns' ] );
        add_action( 'manage_ajax_form_entry_posts_custom_column', [ $this, 'admin_column_content' ], 10, 2 );
        add_filter( 'manage_edit-ajax_form_entry_sortable_columns', [ $this, 'sortable_columns' ] );

        // CSV export
        add_action( 'admin_action_adfs_export_csv', [ $this, 'export_csv' ] );
        add_action( 'restrict_manage_posts', [ $this, 'render_csv_export_button' ] );
        add_action( 'admin_enqueue_scripts', [ $this, 'enqueue_admin_assets' ] );
    }

    /* -----------------------------------------------------------------------
     * Enqueue front-end assets
     * --------------------------------------------------------------------- */
    public function enqueue_assets() {
        wp_enqueue_style(
            'ajax-db-form-saver-css',
            plugins_url( 'assets/css/style.css', __FILE__ ),
            [],
            '2.0'
        );
        wp_enqueue_script(
            'ajax-db-form-saver-js',
            plugins_url( 'js/ajax-db-form-saver.js', __FILE__ ),
            [ 'jquery' ],
            '2.0',
            true
        );
        wp_localize_script( 'ajax-db-form-saver-js', 'AjaxDBFormSaver', [
            'ajax_url' => admin_url( 'admin-ajax.php' ),
            'nonce'    => wp_create_nonce( 'ajax_db_form_nonce' ),
            'messages' => [
                'required'      => 'This field is required.',
                'invalid_email' => 'Please enter a valid email address.',
                'invalid_phone' => 'Please enter a valid phone number.',
                'server_error'  => 'Something went wrong. Please try again.',
            ],
        ] );
    }

    /* -----------------------------------------------------------------------
     * Shortcode: render the form
     * --------------------------------------------------------------------- */
    public function render_form( $atts ) {
        $atts = shortcode_atts( [
            'title'    => 'Contact Us',
            'subtitle' => "We'd love to hear from you. Fill out the form below.",
        ], $atts, 'ajax_db_form' );

        ob_start();
        ?>
        <div class="pfs-form-container">
            <div class="pfs-form-header">
                <h2 class="pfs-form-title"><?php echo esc_html( $atts['title'] ); ?></h2>
                <p class="pfs-form-subtitle"><?php echo esc_html( $atts['subtitle'] ); ?></p>
            </div>

            <form id="ajax-db-form" class="ajax-db-form pfs-form-grid" method="post" novalidate>
                <?php wp_nonce_field( 'ajax_db_form_nonce', 'ajax_db_form_nonce_field' ); ?>

                <!-- Name -->
                <div class="pfs-form-group" id="pfs-group-name">
                    <label class="pfs-label" for="adfs_name">
                        Full Name <span class="pfs-required">*</span>
                    </label>
                    <div class="pfs-input-wrapper">
                        <input
                            class="pfs-input"
                            type="text"
                            name="adfs_name"
                            id="adfs_name"
                            placeholder="John Doe"
                            autocomplete="name"
                        />
                    </div>
                    <span class="pfs-field-error" id="error-adfs_name"></span>
                </div>

                <!-- Email -->
                <div class="pfs-form-group" id="pfs-group-email">
                    <label class="pfs-label" for="adfs_email">
                        Email Address <span class="pfs-required">*</span>
                    </label>
                    <div class="pfs-input-wrapper">
                        <input
                            class="pfs-input"
                            type="email"
                            name="adfs_email"
                            id="adfs_email"
                            placeholder="john@example.com"
                            autocomplete="email"
                        />
                    </div>
                    <span class="pfs-field-error" id="error-adfs_email"></span>
                </div>

                <!-- Phone -->
                <div class="pfs-form-group" id="pfs-group-phone">
                    <label class="pfs-label" for="adfs_phone">
                        Phone Number <span class="pfs-required">*</span>
                    </label>
                    <div class="pfs-input-wrapper">
                        <input
                            class="pfs-input"
                            type="tel"
                            name="adfs_phone"
                            id="adfs_phone"
                            placeholder="+1 (555) 000-0000"
                            autocomplete="tel"
                        />
                    </div>
                    <span class="pfs-field-error" id="error-adfs_phone"></span>
                </div>

                <!-- Subject -->
                <div class="pfs-form-group" id="pfs-group-subject">
                    <label class="pfs-label" for="adfs_subject">
                        Subject <span class="pfs-required">*</span>
                    </label>
                    <div class="pfs-input-wrapper">
                        <input
                            class="pfs-input"
                            type="text"
                            name="adfs_subject"
                            id="adfs_subject"
                            placeholder="How can we help?"
                        />
                    </div>
                    <span class="pfs-field-error" id="error-adfs_subject"></span>
                </div>

                <!-- Message -->
                <div class="pfs-form-group pfs-grid-span-2" id="pfs-group-message">
                    <label class="pfs-label" for="adfs_message">
                        Message <span class="pfs-required">*</span>
                    </label>
                    <div class="pfs-input-wrapper">
                        <textarea
                            class="pfs-textarea"
                            name="adfs_message"
                            id="adfs_message"
                            rows="5"
                            placeholder="Write your message here..."
                        ></textarea>
                    </div>
                    <span class="pfs-field-error" id="error-adfs_message"></span>
                </div>

                <!-- Submit -->
                <div class="pfs-form-group pfs-grid-span-2">
                    <button type="submit" class="pfs-submit-btn" id="pfs-submit-btn">
                        <span class="pfs-btn-spinner"></span>
                        <span class="pfs-btn-text">Send Message</span>
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg>
                    </button>
                </div>

                <!-- Response message (below form) -->
                <div class="pfs-grid-span-2">
                    <div class="pfs-alert-container ajax-db-form-response" id="ajax-db-form-response" role="alert" aria-live="polite"></div>
                </div>
            </form>
        </div>
        <?php
        return ob_get_clean();
    }

    /* -----------------------------------------------------------------------
     * AJAX handler
     * --------------------------------------------------------------------- */
    public function handle_form_submit() {
        // Verify nonce
        if ( ! check_ajax_referer( 'ajax_db_form_nonce', 'nonce', false ) ) {
            wp_send_json_error( [ 'message' => 'Security check failed. Please refresh the page.' ] );
        }

        // Sanitize inputs
        $name    = sanitize_text_field( wp_unslash( $_POST['adfs_name']    ?? '' ) );
        $email   = sanitize_email( wp_unslash( $_POST['adfs_email']   ?? '' ) );
        $phone   = sanitize_text_field( wp_unslash( $_POST['adfs_phone']   ?? '' ) );
        $subject = sanitize_text_field( wp_unslash( $_POST['adfs_subject'] ?? '' ) );
        $message = sanitize_textarea_field( wp_unslash( $_POST['adfs_message'] ?? '' ) );

        // Server-side validation
        $errors = [];

        if ( empty( $name ) ) {
            $errors['adfs_name'] = 'Full name is required.';
        }

        if ( empty( $email ) ) {
            $errors['adfs_email'] = 'Email address is required.';
        } elseif ( ! is_email( $email ) ) {
            $errors['adfs_email'] = 'Please enter a valid email address.';
        }

        if ( empty( $phone ) ) {
            $errors['adfs_phone'] = 'Phone number is required.';
        } elseif ( ! preg_match( '/^[+\d\s\-().]{7,20}$/', $phone ) ) {
            $errors['adfs_phone'] = 'Please enter a valid phone number.';
        }

        if ( empty( $subject ) ) {
            $errors['adfs_subject'] = 'Subject is required.';
        }

        if ( empty( $message ) ) {
            $errors['adfs_message'] = 'Message is required.';
        }

        if ( ! empty( $errors ) ) {
            wp_send_json_error( [ 'message' => 'Please fix the errors below.', 'fields' => $errors ] );
        }

        // Insert post
        $post_id = wp_insert_post( [
            'post_type'   => 'ajax_form_entry',
            'post_title'  => sanitize_text_field( $name . ' — ' . $subject ),
            'post_status' => 'private',
            'meta_input'  => [
                '_adfs_name'    => $name,
                '_adfs_email'   => $email,
                '_adfs_phone'   => $phone,
                '_adfs_subject' => $subject,
                '_adfs_message' => $message,
            ],
        ] );

        if ( is_wp_error( $post_id ) ) {
            wp_send_json_error( [ 'message' => 'Failed to save your submission. Please try again.' ] );
        }

        // Assign taxonomy term (subject as category)
        $term = term_exists( $subject, 'form_entry_subject' );
        if ( ! $term ) {
            $term = wp_insert_term( $subject, 'form_entry_subject' );
        }
        if ( ! is_wp_error( $term ) ) {
            $term_id = is_array( $term ) ? $term['term_id'] : $term;
            wp_set_post_terms( $post_id, [ (int) $term_id ], 'form_entry_subject' );
        }

        wp_send_json_success( [ 'message' => 'Thank you! Your message has been received. We will get back to you soon.' ] );
    }

    /* -----------------------------------------------------------------------
     * Register custom post type
     * --------------------------------------------------------------------- */
    public function register_post_type() {
        $labels = [
            'name'               => _x( 'Form Entries', 'post type general name', 'ajax-db-form-saver' ),
            'singular_name'      => _x( 'Form Entry', 'post type singular name', 'ajax-db-form-saver' ),
            'menu_name'          => _x( 'Form Entries', 'admin menu', 'ajax-db-form-saver' ),
            'all_items'          => __( 'All Entries', 'ajax-db-form-saver' ),
            'view_item'          => __( 'View Entry', 'ajax-db-form-saver' ),
            'search_items'       => __( 'Search Entries', 'ajax-db-form-saver' ),
            'not_found'          => __( 'No entries found.', 'ajax-db-form-saver' ),
            'not_found_in_trash' => __( 'No entries found in Trash.', 'ajax-db-form-saver' ),
        ];

        register_post_type( 'ajax_form_entry', [
            'labels'              => $labels,
            'public'              => false,
            'show_ui'             => true,
            'show_in_menu'        => true,
            'menu_icon'           => 'dashicons-email-alt',
            'capability_type'     => 'post',
            'hierarchical'        => false,
            'supports'            => [ 'title' ],
            'has_archive'         => false,
            'exclude_from_search' => true,
            'rewrite'             => false,
        ] );
    }

    /* -----------------------------------------------------------------------
     * Register taxonomy (Subject categories)
     * --------------------------------------------------------------------- */
    public function register_taxonomy() {
        $labels = [
            'name'              => _x( 'Subjects', 'taxonomy general name', 'ajax-db-form-saver' ),
            'singular_name'     => _x( 'Subject', 'taxonomy singular name', 'ajax-db-form-saver' ),
            'search_items'      => __( 'Search Subjects', 'ajax-db-form-saver' ),
            'all_items'         => __( 'All Subjects', 'ajax-db-form-saver' ),
            'edit_item'         => __( 'Edit Subject', 'ajax-db-form-saver' ),
            'update_item'       => __( 'Update Subject', 'ajax-db-form-saver' ),
            'add_new_item'      => __( 'Add New Subject', 'ajax-db-form-saver' ),
            'new_item_name'     => __( 'New Subject Name', 'ajax-db-form-saver' ),
            'menu_name'         => __( 'Subjects', 'ajax-db-form-saver' ),
            'not_found'         => __( 'No subjects found.', 'ajax-db-form-saver' ),
        ];

        register_taxonomy( 'form_entry_subject', [ 'ajax_form_entry' ], [
            'labels'            => $labels,
            'hierarchical'      => false,
            'public'            => false,
            'show_ui'           => true,
            'show_admin_column' => true,
            'show_in_menu'      => true,
            'rewrite'           => false,
            'query_var'         => false,
        ] );
    }

    /* -----------------------------------------------------------------------
     * Admin meta box — show full entry details
     * --------------------------------------------------------------------- */
    public function add_entry_meta_box() {
        add_meta_box(
            'adfs_entry_details',
            __( 'Submission Details', 'ajax-db-form-saver' ),
            [ $this, 'render_entry_meta_box' ],
            'ajax_form_entry',
            'normal',
            'high'
        );
    }

    public function render_entry_meta_box( $post ) {
        $fields = [
            '_adfs_name'    => 'Full Name',
            '_adfs_email'   => 'Email',
            '_adfs_phone'   => 'Phone',
            '_adfs_subject' => 'Subject',
            '_adfs_message' => 'Message',
        ];
        echo '<table class="form-table pfs-meta-table">';
        foreach ( $fields as $key => $label ) {
            $value = get_post_meta( $post->ID, $key, true );
            echo '<tr>';
            echo '<th><strong>' . esc_html( $label ) . '</strong></th>';
            echo '<td>' . nl2br( esc_html( $value ) ) . '</td>';
            echo '</tr>';
        }
        echo '</table>';
        echo '<p style="color:#64748b;font-size:12px;margin-top:12px;">Submitted: ' . esc_html( get_the_date( 'F j, Y \a\t g:i a', $post ) ) . '</p>';
    }

    /* -----------------------------------------------------------------------
     * Admin list table columns
     * --------------------------------------------------------------------- */
    public function admin_columns( $columns ) {
        $new = [];
        $new['cb']           = $columns['cb'];
        $new['title']        = __( 'Name / Subject', 'ajax-db-form-saver' );
        $new['adfs_email']   = __( 'Email', 'ajax-db-form-saver' );
        $new['adfs_phone']   = __( 'Phone', 'ajax-db-form-saver' );
        $new['taxonomy-form_entry_subject'] = __( 'Subject Category', 'ajax-db-form-saver' );
        $new['adfs_message'] = __( 'Message Preview', 'ajax-db-form-saver' );
        $new['date']         = __( 'Date', 'ajax-db-form-saver' );
        return $new;
    }

    public function admin_column_content( $column, $post_id ) {
        switch ( $column ) {
            case 'adfs_email':
                $email = get_post_meta( $post_id, '_adfs_email', true );
                echo '<a href="mailto:' . esc_attr( $email ) . '">' . esc_html( $email ) . '</a>';
                break;
            case 'adfs_phone':
                echo esc_html( get_post_meta( $post_id, '_adfs_phone', true ) );
                break;
            case 'adfs_message':
                $msg = get_post_meta( $post_id, '_adfs_message', true );
                echo esc_html( wp_trim_words( $msg, 12, '…' ) );
                break;
        }
    }

    public function sortable_columns( $columns ) {
        $columns['adfs_email'] = 'adfs_email';
        return $columns;
    }

    /* -----------------------------------------------------------------------
     * Enqueue admin-only assets (CSS for the export button)
     * --------------------------------------------------------------------- */
    public function enqueue_admin_assets( $hook ) {
        // Only load on the Form Entries list screen
        $screen = get_current_screen();
        if ( ! $screen || $screen->post_type !== 'ajax_form_entry' ) {
            return;
        }
        wp_enqueue_style(
            'ajax-db-form-saver-admin-css',
            plugins_url( 'assets/css/admin.css', __FILE__ ),
            [],
            '2.1'
        );
    }

    /* -----------------------------------------------------------------------
     * Render the "Export CSV" button above the entries list table
     * --------------------------------------------------------------------- */
    public function render_csv_export_button( $post_type ) {
        if ( $post_type !== 'ajax_form_entry' ) {
            return;
        }

        $url = wp_nonce_url(
            add_query_arg(
                [ 'action' => 'adfs_export_csv' ],
                admin_url( 'admin.php' )
            ),
            'adfs_export_csv_nonce'
        );
        ?>
        <a href="<?php echo esc_url( $url ); ?>" class="adfs-export-btn" title="Download all form entries as a CSV file">
            <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24"
                 fill="none" stroke="currentColor" stroke-width="2.2"
                 stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                <polyline points="7 10 12 15 17 10"/>
                <line x1="12" y1="15" x2="12" y2="3"/>
            </svg>
            Export CSV
        </a>
        <?php
    }

    /* -----------------------------------------------------------------------
     * Handle CSV download
     * --------------------------------------------------------------------- */
    public function export_csv() {
        // Capability & nonce check
        if ( ! current_user_can( 'manage_options' ) ) {
            wp_die( __( 'You do not have permission to export entries.', 'ajax-db-form-saver' ) );
        }

        check_admin_referer( 'adfs_export_csv_nonce' );

        // Fetch ALL private entries (no pagination limit)
        $entries = get_posts( [
            'post_type'      => 'ajax_form_entry',
            'post_status'    => 'private',
            'posts_per_page' => -1,
            'orderby'        => 'date',
            'order'          => 'DESC',
        ] );

        // Build filename with current date
        $filename = 'form-entries-' . gmdate( 'Y-m-d' ) . '.csv';

        // Send headers to trigger browser download
        header( 'Content-Type: text/csv; charset=UTF-8' );
        header( 'Content-Disposition: attachment; filename="' . $filename . '"' );
        header( 'Pragma: no-cache' );
        header( 'Expires: 0' );

        // Open output stream
        $output = fopen( 'php://output', 'w' );

        // UTF-8 BOM so Excel opens it correctly
        fputs( $output, "\xEF\xBB\xBF" );

        // Header row
        fputcsv( $output, [
            'ID',
            'Full Name',
            'Email',
            'Phone',
            'Subject',
            'Message',
            'Subject Category',
            'Submitted Date',
        ] );

        // Data rows
        foreach ( $entries as $entry ) {
            $terms    = get_the_terms( $entry->ID, 'form_entry_subject' );
            $category = ( $terms && ! is_wp_error( $terms ) )
                ? implode( ', ', wp_list_pluck( $terms, 'name' ) )
                : '';

            fputcsv( $output, [
                $entry->ID,
                get_post_meta( $entry->ID, '_adfs_name',    true ),
                get_post_meta( $entry->ID, '_adfs_email',   true ),
                get_post_meta( $entry->ID, '_adfs_phone',   true ),
                get_post_meta( $entry->ID, '_adfs_subject', true ),
                get_post_meta( $entry->ID, '_adfs_message', true ),
                $category,
                get_the_date( 'Y-m-d H:i:s', $entry ),
            ] );
        }

        fclose( $output );
        exit;
    }
}

new Ajax_DB_Form_Saver();
