<?php
/**
 * Plugin Name: AJAX DB Form Saver
 * Description: Provides a shortcode to display a form that saves submissions via AJAX to a custom post type.
 * Version: 1.0.0
 * Author: AutoGenerated
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

class Ajax_DB_Form_Saver {
    public function __construct() {
        // Register shortcode.
        add_shortcode('ajax_db_form', [$this, 'render_form']);
        // Enqueue assets.
        add_action('wp_enqueue_scripts', [$this, 'enqueue_assets']);
        // Register AJAX actions.
        add_action('wp_ajax_nopriv_ajax_db_form_submit', [$this, 'handle_form_submit']);
        add_action('wp_ajax_ajax_db_form_submit', [$this, 'handle_form_submit']);
        // Register custom post type for entries.
        add_action('init', [$this, 'register_post_type']);
    }

    /**
     * Enqueue JavaScript and localize AJAX URL.
     */
    public function enqueue_assets() {
        $handle = 'ajax-db-form-saver-js';
        $src = plugins_url('js/ajax-db-form-saver.js', __FILE__);
        wp_enqueue_script($handle, $src, ['jquery'], '1.0', true);
        wp_localize_script($handle, 'AjaxDBFormSaver', [
            'ajax_url' => admin_url('admin-ajax.php'),
            'nonce'    => wp_create_nonce('ajax_db_form_nonce'),
        ]);
    }

    /**
     * Render the form via shortcode.
     */
    public function render_form($atts) {
        $atts = shortcode_atts([
            'title' => 'Contact Us',
        ], $atts, 'ajax_db_form');

        ob_start();
        ?>
        <div class="ajax-db-form-saver">
            <h3><?php echo esc_html($atts['title']); ?></h3>
            <form id="ajax-db-form" method="post">
                <p>
                    <label for="adfs_name">Name</label><br />
                    <input type="text" name="name" id="adfs_name" required />
                </p>
                <p>
                    <label for="adfs_email">Email</label><br />
                    <input type="email" name="email" id="adfs_email" required />
                </p>
                <p>
                    <label for="adfs_message">Message</label><br />
                    <textarea name="message" id="adfs_message" rows="4" required></textarea>
                </p>
                <p>
                    <button type="submit">Send</button>
                </p>
                <div id="ajax-db-form-response" style="margin-top:10px;"></div>
            </form>
        </div>
        <?php
        return ob_get_clean();
    }

    /**
     * Handle AJAX form submission.
     */
    public function handle_form_submit() {
        check_ajax_referer('ajax_db_form_nonce', 'nonce');

        $name    = sanitize_text_field($_POST['name'] ?? '');
        $email   = sanitize_email($_POST['email'] ?? '');
        $message = sanitize_textarea_field($_POST['message'] ?? '');

        if (empty($name) || empty($email) || empty($message)) {
            wp_send_json_error(['message' => 'All fields are required.']);
        }

        $post_id = wp_insert_post([
            'post_type'   => 'ajax_form_entry',
            'post_title'  => $name . ' – ' . $email,
            'post_status' => 'private',
            'meta_input'  => [
                'adfs_message' => $message,
                'adfs_email'   => $email,
                'adfs_name'    => $name,
            ],
        ]);

        if (is_wp_error($post_id)) {
            wp_send_json_error(['message' => 'Failed to save entry.']);
        }

        wp_send_json_success(['message' => 'Thank you! Your message has been received.']);
    }

    /**
     * Register a private custom post type to store form entries.
     */
    public function register_post_type() {
        $labels = [
            'name'               => _x('Form Entries', 'post type general name', 'ajax-db-form-saver'),
            'singular_name'      => _x('Form Entry', 'post type singular name', 'ajax-db-form-saver'),
            'menu_name'          => _x('Form Entries', 'admin menu', 'ajax-db-form-saver'),
            'name_admin_bar'     => _x('Form Entry', 'add new on admin bar', 'ajax-db-form-saver'),
            'add_new'            => _x('Add New', 'entry', 'ajax-db-form-saver'),
            'add_new_item'       => __('Add New Entry', 'ajax-db-form-saver'),
            'edit_item'          => __('Edit Entry', 'ajax-db-form-saver'),
            'view_item'          => __('View Entry', 'ajax-db-form-saver'),
            'all_items'          => __('All Entries', 'ajax-db-form-saver'),
            'search_items'       => __('Search Entries', 'ajax-db-form-saver'),
            'not_found'          => __('No entries found.', 'ajax-db-form-saver'),
        ];

        $args = [
            'labels'             => $labels,
            'public'             => false,
            'show_ui'            => true,
            'show_in_menu'       => true,
            'capability_type'    => 'post',
            'hierarchical'       => false,
            'supports'           => ['title', 'custom-fields'],
            'has_archive'        => false,
            'exclude_from_search'=> true,
        ];

        register_post_type('ajax_form_entry', $args);
    }
}

// Initialize the plugin.
new Ajax_DB_Form_Saver();
?>
